# This is a basic workflow to help you get started with Actions

name: CI Deduplication

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout
      uses: actions/checkout@v2
    - name: Copy test data
      run: aws s3 cp s3://justiceaitestdata ./tests/test_data --region us-east --recursive --no-sign-request
    - name: Copy dockerfile into root
    # Copy  Dockerfile into root due to limitations set by the Github actions worflow
      run: cp docker/Dockerfile.dedup-cpu Dockerfile
      
    - name: Build Docker CPU
    # This will trigger the Docker-Cpu build
      uses: ./ 
